site_name: MarkDown & MkDocs

theme: 
  name: material
  icon:

    # logo: simple/markdown  # icono -> :simple-markdown:
    
    #icono de pagina
    logo: simple/markdown  
    # logo: bootstrap/activity  # icono local 
    
    # iconos de avance y retroceso 
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    

  # carpeta local con extras (opcional)
  custom_dir: overrides
  
  features:
    - content.tabs.link         # pestañas sincronizadas
    - content.code.copy         # botón de copia 
    - content.code.annotate     # botones de anotaciones emergentes

markdown_extensions: 
  # "advertencias"
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # anotaciones
  - attr_list
  - md_in_html
  - pymdownx.superfences

  # grids
  - attr_list
  - md_in_html

  # emojis - iconos
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      # Iconos LOCALES
      options:
        custom_icons:
          - overrides/.icons    # Carpeta local - ruta desde directorio raiz del proyecto

  # pestañas de contenido
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  # matematica
  - pymdownx.arithmatex:
      generic: true

  # Tablas (activado por defecto)
  - tables

  # formato pestañas - 'slugify' (v9.6 0 más reciente)
  # - pymdownx.tabbed:
  #     slugify: !!python/object/apply:pymdownx.slugs.slugify
  #       kwds:
  #         case: lower

  #bloques codigo
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite   # habilita remarcado de renglones
  - pymdownx.snippets       # habilita importar código de otros archivos
  - pymdownx.superfences    # habilita anidado de otros contenidos

  # notas al pie
  - footnotes
  
  # footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde







extra_css:
  - stylesheets/extra.css
  - stylesheets/iconos_demo.css
  #katex
  - https://unpkg.com/katex@0/dist/katex.min.css


extra_javascript:
  # mathjax
  # - javascripts/mathjax.js
  # - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  # katex
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

  # Tablas ordenables - TableSort
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js        # archivo local


plugins:
  - social:
      cards_layout: default/purple
      cards_layout_options:
        # background_color: "#0FF1CE8F"
        background_color: "#0FF1CEFF"

      debug: true

  # lectura tablas desde archivo
  # - search
  # - table-reader




nav:
  - Indice: index.md
  - MarkDown:  
    - Básico: markdown/markdown_basico.md
    - Fórmulas matemáticas: markdown/markdown_matematica.md
  - MkDocs-Material: 
    - Referencia: 
      - Advertencias: mkdocs-material/referencia/admonitions.md
      - Bloques de código: mkdocs-material/referencia/bloques_codigo.md
      - Tablas: mkdocs-material/referencia/tablas.md
      - Anotaciones: mkdocs-material/referencia/anotaciones.md
      - Grillas (grids): mkdocs-material/referencia/grids.md
      - Soporte para matemáticas: mkdocs-material/referencia/soporte_matematica.md
      - Pestañas (tabs): mkdocs-material/referencia/tabs.md
      - Íconos y Emojis: mkdocs-material/referencia/iconos_emojis.md
      - Notas al Pie (footnotes): mkdocs-material/referencia/footnotes.md
      - Formateo: mkdocs-material/referencia/formateo.md







