site_name: MarkDown & MkDocs


theme: 
  name: material
  # favicon: images/favicon.png   # no anda
  icon:
    #icono de pagina
    logo: simple/markdown  
    # logo: bootstrap/activity  # icono local 
    # iconos de avance y retroceso 
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    # Icono de repositorio
    repo: fontawesome/brands/github
    # Icono de acciones de repositorio
    edit: material/pencil 
    view: material/eye

  # # fuentes remotas
  # font:
  #   text: Matemasie
  #   code: Grey Qo

  # carpeta local con extras (opcional)
  custom_dir: overrides
  
  features:
    - content.tabs.link         # pestañas sincronizadas
    - content.code.copy         # botón de copia 
    - content.code.annotate     # botones de anotaciones emergentes

    - search.suggest      # sugerencias en caja de búsqueda
    - search.highlight  # remarcado en página
    - search.share      # link 'compartir' en caja de búsqueda
    # - search.exclude

    - navigation.instant
    - navigation.instant.progress   # progreso de carga (conexiones lentas)
    - navigation.tracking
    # pestañas de contenido
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    # - navigation.prune 
    # - navigation.indexes 
    - toc.follow
    # - toc.integrate   # integra indice derecho (secciones) adentro del izquierdo (rutas)
    - navigation.top  # boton emergente para volver al inicio  - aparece al intentar subir con el scroll

    # Pie de pagina
    - navigation.footer

    # header y anuncios
    - header.autohide
    - announce.dismiss

    # acciones sobre repositorio
    - content.action.edit
    - content.action.view


  # soporte de idiomas
  language: es    # Idioma predefinido
  # direction: ltr

  # Opciones de temas y colores
  palette: 
    # Cambio de paleta al modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Cambia al modo oscuro 
      primary: indigo
      accent: blue
    # Cambio de paleta al modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4     # icono
        name: Cambia al modo claro      # mensaje
      primary: deep purple
      accent: pink



# Repositorio
repo_url: https://github.com/MarceloMarot/MarkDown_MKDocs/
repo_name: MarkDown_MKDocs
edit_uri: edit/master/docs/



markdown_extensions: 
  # "advertencias"
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # anotaciones
  - attr_list
  - md_in_html
  - pymdownx.superfences

  # grids
  - attr_list
  - md_in_html

  # emojis - iconos
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      # Iconos LOCALES
      options:
        custom_icons:
          - overrides/.icons    # Carpeta local - ruta desde directorio raiz del proyecto

  # pestañas de contenido
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  # matematica
  - pymdownx.arithmatex:
      generic: true

  # Tablas (activado por defecto)
  - tables

  # formato pestañas - 'slugify' (v9.6 0 más reciente)
  # - pymdownx.tabbed:
  #     slugify: !!python/object/apply:pymdownx.slugs.slugify
  #       kwds:
  #         case: lower

  #bloques codigo
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite   # habilita remarcado de renglones
  - pymdownx.snippets       # habilita importar código de otros archivos
  - pymdownx.superfences    # habilita anidado de otros contenidos

  # notas al pie
  - footnotes
  
  # formateo
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde




extra:
#   # Idiomas seleccionables
#   alternate:
#     - name: Change to English
#       link: /en/    # ruta relativa al contenido en inglés
#       lang: en
#     - name: Cambiar a Español
#       link: /       # ruta relativa al contenido en español
#       lang: es
# # menu de cookies
# #  consent:
#     title: Cookie consent
#     description: 
#       We use cookies to recognize your repeated visits and preferences, as well
#       as to measure the effectiveness of our documentation and whether users
#       find what they're searching for. With your consent, you're helping us to
#       make our documentation better.
#     actions:
#       - accept
#       - manage 
  # generator: false
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/
      name: Ir a Mastodon
    - icon: fontawesome/solid/paper-plane
      link: mailto:<email-address>
      name: Enviar correo


# copyright: Copyright &copy; 2030 Aquiles Brinco


extra_css:
  - stylesheets/extra.css
  - stylesheets/iconos_demo.css
  # - stylesheets/colores_custom.css
  - stylesheets/colores_codigo.css
  - stylesheets/ancho_maximo.css
  #katex
  - https://unpkg.com/katex@0/dist/katex.min.css


extra_javascript:
  # mathjax
  # - javascripts/mathjax.js
  # - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  # katex
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

  # Tablas ordenables - TableSort
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js        # archivo local


plugins:
  - social:
      cards_layout: default/purple
      cards_layout_options:
        # background_color: "#0FF1CE8F"
        background_color: "#0FF1CEFF"

      debug: true

  # lectura tablas desde archivo
  # - search
  # - table-reader

  # privacidad - hace copia local de contenidos remotos
  - privacy

  # busqueda
  - search

  # fechas de repositorio
  - git-revision-date-localized:
      enabled: true
      enable_creation_date: true
      # type: date        # fecha
      # type: datetime    # fecha y hora
      # type: iso_date    # fecha ISO (sólo numeros)
      # type: iso_datetime  # fecha ISO (sólo numeros)
      type: timeago       # tiempo desde publicación
      fallback_to_build_date: true


nav:
  - Indice: index.md
  - MarkDown:  
    - Básico: markdown/markdown_basico.md
    - Fórmulas matemáticas: markdown/markdown_matematica.md
  - MkDocs-Material: 

    - Primeros pasos: mkdocs-material/basico.md
    
    - Configuración: 
      - Lenguaje: mkdocs-material/setup/lenguaje.md
      - Temas y colores: mkdocs-material/setup/colores_temas.md
      - Fuentes: mkdocs-material/setup/fuentes.md
      - Búsqueda:  mkdocs-material/setup/busqueda.md
      - Navegación:  mkdocs-material/setup/navegacion.md
      - Sobreescritura:  mkdocs-material/setup/sobreescritura.md
      - Componentes:  mkdocs-material/setup/componentes.md


    - Referencia: 
      - Encabezamientos: mkdocs-material/referencia/headers.md
      - Advertencias: mkdocs-material/referencia/admonitions.md
      - Bloques de código: mkdocs-material/referencia/bloques_codigo.md
      - Tablas: mkdocs-material/referencia/tablas.md
      - Anotaciones: mkdocs-material/referencia/anotaciones.md
      - Grillas (grids): mkdocs-material/referencia/grids.md
      - Soporte para matemáticas: mkdocs-material/referencia/soporte_matematica.md
      - Pestañas (tabs): mkdocs-material/referencia/tabs.md
      - Íconos y Emojis: mkdocs-material/referencia/iconos_emojis.md
      - Notas al Pie (footnotes): mkdocs-material/referencia/footnotes.md
      - Formateo: mkdocs-material/referencia/formateo.md







