site_name: MarkDown & MkDocs

theme: 
  name: material
  icon:
    logo: simple/markdown  # :simple-markdown:

  # pestanñas sincronizadas
  features:
    - content.tabs.link


markdown_extensions: 
  # admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # anotaciones
  - attr_list
  - md_in_html
  - pymdownx.superfences

  # grids
  - attr_list
  - md_in_html

  # emojis - iconos
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # pestañas de contenido
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  # matematica
  - pymdownx.arithmatex:
      generic: true

  # formato pestañas - 'slugify' (v9.6)
  # - pymdownx.tabbed:
  #     slugify: !!python/object/apply:pymdownx.slugs.slugify
  #       kwds:
  #         case: lower



extra_css:
  - stylesheets/extra.css
  #katex
  - https://unpkg.com/katex@0/dist/katex.min.css


extra_javascript:
  # mathjax
  # - javascripts/mathjax.js
  # - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  # katex
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

plugins:
  - social:
      cards_layout: default/purple
      cards_layout_options:
        # background_color: "#0FF1CE8F"
        background_color: "#0FF1CEFF"

      debug: true






nav:
  - Indice: index.md
  - MarkDown:  
    - Básico: markdown/markdown_basico.md
    - Fórmulas matemáticas: markdown/markdown_matematica.md
  - MkDocs-Material: 
    - Referencia: 
      - Advertencias: mkdocs-material/referencia/admonitions.md
      - Grillas (grids): mkdocs-material/referencia/grids.md
      - Soporte para matemáticas: mkdocs-material/referencia/soporte_matematica.md
      - Pestañas (tabs): mkdocs-material/referencia/tabs.md
      - Bloques de código: mkdocs-material/referencia/bloques_codigo.md
      - Anotaciones: mkdocs-material/referencia/anotaciones.md







